/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/nasa-jsc-control-room.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['0']: THREE.Mesh
    ['0_1']: THREE.Mesh
    ['0_2']: THREE.Mesh
    ['0_3']: THREE.Mesh
    ['0_4']: THREE.Mesh
    ['0_5']: THREE.Mesh
    ['0_6']: THREE.Mesh
    ['0_7']: THREE.Mesh
    ['0_8']: THREE.Mesh
    ['0_9']: THREE.Mesh
    ['0_10']: THREE.Mesh
    ['0_11']: THREE.Mesh
    ['0_12']: THREE.Mesh
    ['0_13']: THREE.Mesh
    ['0_14']: THREE.Mesh
    ['0_15']: THREE.Mesh
    ['0_16']: THREE.Mesh
    ['0_17']: THREE.Mesh
    ['0_18']: THREE.Mesh
    ['0_19']: THREE.Mesh
    ['0_20']: THREE.Mesh
    ['0_21']: THREE.Mesh
    ['0_22']: THREE.Mesh
    ['0_23']: THREE.Mesh
    ['0_24']: THREE.Mesh
    ['0_25']: THREE.Mesh
    ['0_26']: THREE.Mesh
    ['0_27']: THREE.Mesh
    ['0_28']: THREE.Mesh
    ['0_29']: THREE.Mesh
    ['0_30']: THREE.Mesh
    ['0_31']: THREE.Mesh
    ['0_32']: THREE.Mesh
    ['0_33']: THREE.Mesh
    ['0_34']: THREE.Mesh
    ['0_35']: THREE.Mesh
    ['0_36']: THREE.Mesh
    ['0_37']: THREE.Mesh
    ['0_38']: THREE.Mesh
    ['0_39']: THREE.Mesh
    ['0_40']: THREE.Mesh
    ['0_41']: THREE.Mesh
    ['0_42']: THREE.Mesh
    ['0_43']: THREE.Mesh
    ['0_44']: THREE.Mesh
  }
  materials: {
    Keyboards: THREE.MeshStandardMaterial
    cabnet: THREE.MeshStandardMaterial
    ceiling: THREE.MeshStandardMaterial
    console_back: THREE.MeshStandardMaterial
    console_body: THREE.MeshStandardMaterial
    console_desk: THREE.MeshStandardMaterial
    console_face: THREE.MeshStandardMaterial
    console_nameplat: THREE.MeshStandardMaterial
    console_namepla1: THREE.MeshStandardMaterial
    console_namepla2: THREE.MeshStandardMaterial
    console_namepla3: THREE.MeshStandardMaterial
    console_namepla4: THREE.MeshStandardMaterial
    console_namepla5: THREE.MeshStandardMaterial
    console_namepla6: THREE.MeshStandardMaterial
    console_namepla7: THREE.MeshStandardMaterial
    console_namepla8: THREE.MeshStandardMaterial
    console_namepla9: THREE.MeshStandardMaterial
    console_namepl10: THREE.MeshStandardMaterial
    console_namepl11: THREE.MeshStandardMaterial
    console_namepl12: THREE.MeshStandardMaterial
    console_namepl13: THREE.MeshStandardMaterial
    console_namepl14: THREE.MeshStandardMaterial
    console_namepl15: THREE.MeshStandardMaterial
    crstation_1: THREE.MeshStandardMaterial
    crstation_2: THREE.MeshStandardMaterial
    edge: THREE.MeshStandardMaterial
    far_right: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
    keyboard_special: THREE.MeshStandardMaterial
    lights: THREE.MeshStandardMaterial
    mid: THREE.MeshStandardMaterial
    midle: THREE.MeshStandardMaterial
    picture1: THREE.MeshStandardMaterial
    picture2: THREE.MeshStandardMaterial
    picture3: THREE.MeshStandardMaterial
    picture4: THREE.MeshStandardMaterial
    picture5: THREE.MeshStandardMaterial
    picture6: THREE.MeshStandardMaterial
    projector1: THREE.MeshStandardMaterial
    right: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    screens: THREE.MeshStandardMaterial
    wall: THREE.MeshStandardMaterial
    wall_screen: THREE.MeshStandardMaterial
    wall_top: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/nasa-jsc-control-room.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['0'].geometry} material={materials.Keyboards} />
        <mesh geometry={nodes['0_1'].geometry} material={materials.cabnet} />
        <mesh geometry={nodes['0_2'].geometry} material={materials.ceiling} />
        <mesh geometry={nodes['0_3'].geometry} material={materials.console_back} />
        <mesh geometry={nodes['0_4'].geometry} material={materials.console_body} />
        <mesh geometry={nodes['0_5'].geometry} material={materials.console_desk} />
        <mesh geometry={nodes['0_6'].geometry} material={materials.console_face} />
        <mesh geometry={nodes['0_7'].geometry} material={materials.console_nameplat} />
        <mesh geometry={nodes['0_8'].geometry} material={materials.console_namepla1} />
        <mesh geometry={nodes['0_9'].geometry} material={materials.console_namepla2} />
        <mesh geometry={nodes['0_10'].geometry} material={materials.console_namepla3} />
        <mesh geometry={nodes['0_11'].geometry} material={materials.console_namepla4} />
        <mesh geometry={nodes['0_12'].geometry} material={materials.console_namepla5} />
        <mesh geometry={nodes['0_13'].geometry} material={materials.console_namepla6} />
        <mesh geometry={nodes['0_14'].geometry} material={materials.console_namepla7} />
        <mesh geometry={nodes['0_15'].geometry} material={materials.console_namepla8} />
        <mesh geometry={nodes['0_16'].geometry} material={materials.console_namepla9} />
        <mesh geometry={nodes['0_17'].geometry} material={materials.console_namepl10} />
        <mesh geometry={nodes['0_18'].geometry} material={materials.console_namepl11} />
        <mesh geometry={nodes['0_19'].geometry} material={materials.console_namepl12} />
        <mesh geometry={nodes['0_20'].geometry} material={materials.console_namepl13} />
        <mesh geometry={nodes['0_21'].geometry} material={materials.console_namepl14} />
        <mesh geometry={nodes['0_22'].geometry} material={materials.console_namepl15} />
        <mesh geometry={nodes['0_23'].geometry} material={materials.crstation_1} />
        <mesh geometry={nodes['0_24'].geometry} material={materials.crstation_2} />
        <mesh geometry={nodes['0_25'].geometry} material={materials.edge} />
        <mesh geometry={nodes['0_26'].geometry} material={materials.far_right} />
        <mesh geometry={nodes['0_27'].geometry} material={materials.floor} />
        <mesh geometry={nodes['0_28'].geometry} material={materials.keyboard_special} />
        <mesh geometry={nodes['0_29'].geometry} material={materials.lights} />
        <mesh geometry={nodes['0_30'].geometry} material={materials.mid} />
        <mesh geometry={nodes['0_31'].geometry} material={materials.midle} />
        <mesh geometry={nodes['0_32'].geometry} material={materials.picture1} />
        <mesh geometry={nodes['0_33'].geometry} material={materials.picture2} />
        <mesh geometry={nodes['0_34'].geometry} material={materials.picture3} />
        <mesh geometry={nodes['0_35'].geometry} material={materials.picture4} />
        <mesh geometry={nodes['0_36'].geometry} material={materials.picture5} />
        <mesh geometry={nodes['0_37'].geometry} material={materials.picture6} />
        <mesh geometry={nodes['0_38'].geometry} material={materials.projector1} />
        <mesh geometry={nodes['0_39'].geometry} material={materials.right} />
        <mesh geometry={nodes['0_40'].geometry} material={materials.screen} />
        <mesh geometry={nodes['0_41'].geometry} material={materials.screens} />
        <mesh geometry={nodes['0_42'].geometry} material={materials.wall} />
        <mesh geometry={nodes['0_43'].geometry} material={materials.wall_screen} />
        <mesh geometry={nodes['0_44'].geometry} material={materials.wall_top} />
      </group>
    </group>
  )
}

useGLTF.preload('/nasa-jsc-control-room.glb')
