export { InfoPanel } from '../InfoPanel'
export { ScreenPanel } from './ScreenPanel'
export { ConsolePanel } from './ConsolePanel'
export { StationPanel } from './StationPanel'
export type { PanelContent } from '@/data/panel-content'
